// <auto-generated />
using ApplicationRegistry.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApplicationRegistry.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230820174832_ApplicationRegistryInitialMigration")]
    partial class ApplicationRegistryInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApplicationRegistry.Data.Models.ApplicationDataModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Applications");

                    b.HasData(
                        new
                        {
                            Code = "NOTIFICATIONS",
                            Name = "Notifications System"
                        });
                });

            modelBuilder.Entity("ApplicationRegistry.Data.Models.EventDataModel", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code", "ApplicationCode");

                    b.HasIndex("ApplicationCode");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Code = "NOTIFICATIONS_WEBHOOK_CREATED",
                            ApplicationCode = "NOTIFICATIONS",
                            Name = "WebbHook Created"
                        },
                        new
                        {
                            Code = "NOTIFICATIONS_WEBHOOK_REMOVED",
                            ApplicationCode = "NOTIFICATIONS",
                            Name = "WebbHook Removed"
                        });
                });

            modelBuilder.Entity("ApplicationRegistry.Data.Models.EventDataModel", b =>
                {
                    b.HasOne("ApplicationRegistry.Data.Models.ApplicationDataModel", "Application")
                        .WithMany("Events")
                        .HasForeignKey("ApplicationCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("ApplicationRegistry.Data.Models.ApplicationDataModel", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
